const DATABASE_URL = process.env.DATABASE_URL
const ALCHEMY_API_KEY = process.env.ALCHEMY_API_KEY
const BEACON_DEPOSIT_CONTRACT = process.env.BEACON_DEPOSIT_CONTRACT
const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID

export {
  DATABASE_URL,
  ALCHEMY_API_KEY,
  BEACON_DEPOSIT_CONTRACT,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID,
}