version: "3.7"

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - "3000:3000"
    environment:
      - TELEGRAM_BOT_TOKEN=<your-telegram-bot-token>
      - TELEGRAM_CHAT_ID=<your-telegram-chat-id>
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus

  tracker:
    build:
      context: .
      dockerfile: Dockerfile.tracker
    ports:
      - "4000:4000"
    depends_on:
      - grafana
      - prometheus
    environment:
      - DATABASE_URL=mongodb+srv://<username>:<password>@cluster0.mongodb.net/<dbname>?retryWrites=true&w=majority
      - NOTIFICATION_SERVICE_URL=http://localhost:3000/api/notifications
      - ALCHEMY_API_KEY=<your-alchemy-api-key>
      - BEACON_DEPOSIT_CONTRACT=<your-contract-address></your-contract-address>
      - TELEGRAM_BOT_TOKEN=<your-telegram-bot-token>
      - TELEGRAM_CHAT_ID=<your-telegram-chat-id>

volumes:
  grafana_data:
  prometheus_data:
